/**
 * A straightforward program to find the 2nd most expensive product
 * 
 * Copyright (C) 2024 raodm@miamioh.edu
 */

#define MYSQLPP_MYSQL_HEADERS_BURIED
#include <mysql++/mysql++.h>
#include <iostream>
#include <string>
#include <sstream>
#include <unordered_map>
#include <boost/format.hpp>

// It is ok to use the following namespace delarations in C++ source
// files only. They must never be used in header files.
using namespace std;
using namespace std::string_literals;

/** Ideally, prototype declarations should be avoided. However, it is 
 * being used here just to organize this 
 * solution into a section that students should not modify.  
 */
std::string url_decode(std::string str);

// Synonym used to streamline the source code
using StrStrMap = std::unordered_map<std::string, std::string>;

/**
 * A general and easy approach for processing HTTP inputs is to 
 * extract them into an unordered_map (yes, exactly as it was done in 
 * exercise9).  Implement the following extractParams method to process 
 * POST inputs to extract inputs and values into an unordered_map. For example, 
 * given the inputs "name=raodm&id=123&info=exam2 " the method should return 
 * the map {{"name", "raodm"}, {"id", "123"}, {"info", "exam"}} 
 * 
 * @note std::getline with delimiter character will come in handy to 
 * reach each name-value pair. 
 */
StrStrMap extractParams(const std::string& inputs) {
    // Convenience stream for processing inputs
    std::istringstream is(inputs);

    StrStrMap params;
    for (std::string name, val; std::getline(is, name, '=') && 
         std::getline(is, val, '&'); params[name] = url_decode(val)) {}
    return params;

}

/**
 * A simple class to encapsulate basic information about a product.
 */
class Product {
public:
  std::string pname;
  double price = 0.0;
};

/**
 * For this question, assume that the extractParams method 
 * in the previous question has been correctly implemented. 
 * Complete the following program to return the 2nd most 
 * expensive product with the given name. The inputs to the 
 * method is the 1-line generated by submitting the 
 * following HTML form:
 * 
 *   <form action="ex19.cgi" method="post" target="result">
 *     <p>Manufacturer: <input type="text" name="manu"></p>
 *     <p>Cost: <input type="number" name="cost"></p>
 *     <p><input type="submit" value="Find"></p>
 *   </form>      
 * 
 * \param[in] myDB The database connection to be used to run queries.
 */
Product get2ndExpensive(mysqlpp::Connection& myDB) {
    // Setup the query to run to get products soted on cost
    
    mysqlpp::Query query = myDB.query();

    std::string postData;
    std::getline(std::cin, postData);
    StrStrMap params = extractParams(postData);
    query << "SELECT pname, price FROM Product "
        << "WHERE manufacturer = " << mysqlpp::quote << params["manu"]
        << " ORDER BY price DESC LIMIT 1 OFFSET 1";
mysqlpp::StoreQueryResult res = query.store();
    Product p;
    if (res && res.num_rows() > 0) {
        p.pname = (std::string)res[0]["pname"];
        p.price = res[0]["price"];
    }
    return p;
}

// --------------------------------------------------------------------
//  DO  NOT   MODIFY  CODE  BELOW  THIS  LINE
// --------------------------------------------------------------------

/** Convenience method to decode HTML/URL encoded strings.

    This method must be used to decode query string parameters
    supplied along with GET request.  This method converts URL encoded
    entities in the from %nn (where 'n' is a hexadecimal digit) to
    corresponding ASCII characters.

    \param[in] str The string to be decoded.  If the string does not
    have any URL encoded characters then this original string is
    returned.  So it is always safe to call this method!

    \return The decoded string.
*/
std::string url_decode(std::string str) {
    // Decode entities in the from "%xx"
    size_t pos = 0;
    while ((pos = str.find_first_of("%+", pos)) != std::string::npos) {
        switch (str.at(pos)) {
            case '+': str.replace(pos, 1, " ");
            break;
            case '%': {
                std::string hex = str.substr(pos + 1, 2);
                char ascii = std::stoi(hex, nullptr, 16);
                str.replace(pos, 3, 1, ascii);
            }
        }
        pos++;
    }
    return str;
}

/**
 * A convenience format-string that can be used to generate the
 * html response.
 */
const std::string HTMLResult = 
    "Content-Type: text/html\r\n\r\n"
    "<html><body><pre>\n"
    "2nd most expensive product information:\n"
    "Product name: %1%\n"
    "Cost        : %2%\n"
    "</pre></body></html>\n";

/**
 * The main method creates a connection, calls the get2ndExpensive method, and
 * prints the results in a HTML format.
 */
int main() {
    // Connect to the database to run the query to find user
    mysqlpp::Connection myDB("cse278s19", "os1.csi.miamioh.edu", "cse278s19",
            "rbHkqL64VpcJ2ezj");
    // Call the method under test and print the result.
    const Product result = get2ndExpensive(myDB);
    // Print the result as an HTML to render correctly on a web-browser
    std::cout << boost::format(HTMLResult) % result.pname % result.price;
    return 0;
}

// End of source code
